# Generated by Django 3.0.6 on 2020-05-15 05:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200513_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinput',
            name='post_key',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=6, unique=True),
        ),
    ]
