# Generated by Django 3.0.6 on 2020-05-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_postinput_post_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinput',
            name='post_key',
            field=models.CharField(blank=True, default='09eggj', editable=False, max_length=6, unique=True),
        ),
    ]
