# Generated by Django 3.0.6 on 2020-05-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200515_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinput',
            name='post_key',
            field=models.CharField(blank=True, default='dybcue', editable=False, max_length=6, unique=True),
        ),
    ]
