# Generated by Django 3.0.6 on 2020-05-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200516_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinput',
            name='post_key',
            field=models.CharField(blank=True, default='e1vcyd', editable=False, max_length=6, unique=True),
        ),
    ]
