# Generated by Django 3.0.6 on 2020-05-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200516_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinput',
            name='post_key',
            field=models.CharField(blank=True, default='1zhpuo', editable=False, max_length=6, unique=True),
        ),
    ]
