# Generated by Django 3.0.6 on 2020-05-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200517_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinput',
            name='post_key',
            field=models.CharField(blank=True, default='39x9t9', editable=False, max_length=6),
        ),
    ]
