# Generated by Django 3.0.6 on 2020-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200517_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinput',
            name='post_key',
            field=models.CharField(blank=True, default='kkqn6t', editable=False, max_length=6),
        ),
    ]
