# Generated by Django 3.0.6 on 2020-05-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20200517_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinput',
            name='post_key',
            field=models.CharField(blank=True, default='8lkx7h', editable=False, max_length=6),
        ),
    ]
