# Generated by Django 3.0.6 on 2020-05-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200517_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postinput',
            name='post_key',
        ),
        migrations.AddField(
            model_name='postinput',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
