# Generated by Django 3.0.6 on 2020-05-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20200518_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postinput',
            name='image',
        ),
        migrations.AddField(
            model_name='postinput',
            name='post_key',
            field=models.CharField(blank=True, default='avkgjo', editable=False, max_length=6),
        ),
    ]
